icons = {
    'addition' : 'images\\plus.ico',
    'subtraction' : 'images\\minus.ico',
    'multiplication' : 'images\\multiply.ico',
    'division' : 'images\\divide.ico',
}

config = {
            '1 min' : {
                    'addition' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'subtraction' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'multiplication' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'division' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 8,
                                    'y_max' : 100,
                                    'zoom' : 2,
                                    'rest' : True,
                                 },
                 },
            '30 sec' : {
                    'addition' : {
                                    'timeout' : 30,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'subtraction' : {
                                    'timeout' : 30,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'multiplication' : {
                                    'timeout' : 30,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'division' : {
                                    'timeout' : 30,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 8,
                                    'y_max' : 100,
                                    'zoom' : 2,
                                    'rest' : True,
                                 },
                 },
            '10 sec' : { #default values
                    'addition' : {
                                    'timeout' : 10,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'subtraction' : {
                                    'timeout' : 10,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'multiplication' : {
                                    'timeout' : 10,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'division' : {
                                    'timeout' : 10,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 8,
                                    'y_max' : 100,
                                    'zoom' : 2,
                                    'rest' : True,
                                 },
                 },
            '5 sec' : {
                    'addition' : {
                                    'timeout' : 5,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'subtraction' : {
                                    'timeout' : 5,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'multiplication' : {
                                    'timeout' : 5,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'division' : {
                                    'timeout' : 5,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 8,
                                    'y_max' : 100,
                                    'zoom' : 2,
                                    'rest' : True,
                                 },
                 },
            '1 min - Division ohne Rest' : {
                    'addition' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'subtraction' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'multiplication' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 2,
                                    'y_max' : 10,
                                    'zoom' : 3,
                                 },
                    'division' : {
                                    'timeout' : 60,
                                    'x_min' : 2,
                                    'x_max' : 10,
                                    'y_min' : 8,
                                    'y_max' : 100,
                                    'zoom' : 2,
                                    'rest' : False,
                                 },
                 },
      }